# 从 pydantic 库导入 BaseModel 和 Field
# BaseModel: 数据模型基类，提供自动类型校验和序列化能力
# Field: 为字段添加元信息（如描述、校验规则等）
from pydantic import BaseModel, Field


# 定义"对话响应"数据模型
# 当 AI Agent 处理完用户的请求后，会将最终结果封装成这个格式返回给前端
# 注意：这是非流式（一次性返回全部结果）的响应格式
# 流式传输的格式定义在 stream_events.py 中
class ChatResponse(BaseModel):
    # 链路追踪 ID（必填）
    # 将请求时的 trace_id 原样带回响应中
    # 前端或监控系统可以通过这个 ID 将请求和响应关联起来，方便日志溯源和问题排查
    trace_id: str = Field(..., description="Request trace identifier")

    # AI 识别出的用户意图（必填）
    # AI 在回答之前会先判断用户这次提问的目的是什么
    # 例如："seek_hint"（寻求提示）、"debug_help"（Debug 求助）、"explain_concept"（概念解释）
    # 前端可以根据 intent 的值来决定展示什么风格的 UI（例如提示模式还是解析模式）
    intent: str = Field(..., description="Detected top-level intent")

    # AI 最终生成的回答正文（必填）
    # 这是实际展示给用户的核心内容，通常是格式化的 Markdown 文本
    answer: str = Field(..., description="Final answer generated by the graph")

    # AI 对本次回答的置信度（必填）
    # 取值范围是 [0.0, 1.0]，值越高表示 AI 对自己答案越有把握
    # `ge=0.0` 表示 greater than or equal to 0.0（大于等于 0）
    # `le=1.0` 表示 less than or equal to 1.0（小于等于 1）
    # Pydantic 会自动校验这个数值范围，超出范围会抛出验证错误
    # 前端可以据此显示置信度条，或者当置信度过低时给出额外提示
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the current answer")

    # AI 建议用户的下一步操作（必填）
    # 例如："尝试修改第8行的边界条件后重新提交" 或 "建议先理解二分查找的基本原理"
    # 旨在引导、驱动用户持续学习，而不仅仅是给出答案就结束
    next_action: str = Field(..., description="Most useful next step for the user")
