from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    trace_id: str = Field(..., description="Request trace identifier")
    intent: str = Field(..., description="Detected top-level intent")
    answer: str = Field(..., description="Final answer generated by the graph")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the current answer")
    next_action: str = Field(..., description="Most useful next step for the user")
