from app.schemas.training_plan_request import QuestionCandidate, TrainingPlanRequest
from app.schemas.training_plan_response import TrainingPlanResponse
from app.services.training_planner import build_training_plan


def test_build_training_plan_delegates_to_llm_service(monkeypatch):
    import app.services.training_planner as planner_module  # noqa: WPS433

    monkeypatch.setattr(
        planner_module,
        "build_training_plan_with_llm",
        lambda request: TrainingPlanResponse.model_validate(
            {
                "current_level": "advanced",
                "target_direction": "graph_search",
                "weak_points": "shortest path",
                "strong_points": "array basics",
                "plan_title": "LLM Graph Search Plan",
                "plan_goal": "Focus on shortest path stability.",
                "ai_summary": "Generated by model.",
                "tasks": [
                    {
                        "task_type": "question",
                        "question_id": 101,
                        "exam_id": None,
                        "title_snapshot": "Two Sum",
                        "task_order": 1,
                        "recommended_reason": "Model selected task.",
                        "knowledge_tags_snapshot": "graph",
                        "due_time": None,
                    }
                ],
            }
        ),
    )

    request = TrainingPlanRequest(
        trace_id="phase3-llm",
        user_id=1,
        current_level="starter",
        target_direction="algorithm_foundation",
        candidate_questions=[
            QuestionCandidate(
                question_id=101,
                title="Two Sum",
                difficulty=1,
                algorithm_tag="array",
                knowledge_tags="hash table",
                estimated_minutes=12,
            ),
        ],
    )

    plan = build_training_plan(request)

    assert plan.plan_title == "LLM Graph Search Plan"
    assert plan.current_level == "advanced"
    assert plan.tasks[0].recommended_reason == "Model selected task."


def test_build_training_plan_raises_when_llm_generation_fails(monkeypatch):
    import app.services.training_planner as planner_module  # noqa: WPS433

    def raise_llm_failure(_request):
        raise RuntimeError("未配置可用的大模型。")

    monkeypatch.setattr(planner_module, "build_training_plan_with_llm", raise_llm_failure)

    request = TrainingPlanRequest(
        trace_id="phase3-failure",
        user_id=1,
        current_level="starter",
        target_direction="algorithm_foundation",
        candidate_questions=[
            QuestionCandidate(
                question_id=101,
                title="Two Sum",
                difficulty=1,
                algorithm_tag="array",
                knowledge_tags="hash table",
                estimated_minutes=12,
            ),
        ],
    )

    try:
        build_training_plan(request)
    except RuntimeError as exc:
        assert str(exc) == "未配置可用的大模型。"
    else:
        raise AssertionError("expected RuntimeError when llm generation fails")
