from app.runtime.engine import execute_training_plan_request
from app.runtime.enums import RiskLevel, RunStatus, TaskType
from app.runtime.models import (
    EvidenceState,
    ExecutionState,
    GuardrailState,
    OutcomeState,
    RequestContext,
    UnifiedAgentState,
    WriteIntent,
)
from app.schemas.training_plan_request import QuestionCandidate, TrainingPlanRequest


def test_execute_training_plan_request_returns_llm_runtime_state(monkeypatch):
    import app.runtime.engine as engine_module  # noqa: WPS433

    monkeypatch.setattr(
        engine_module,
        "execute_training_plan_with_llm",
        lambda request: UnifiedAgentState(
            request=RequestContext(
                trace_id=request.trace_id,
                user_id=str(request.user_id),
                task_type=TaskType.TRAINING_PLAN,
                user_message="生成训练计划。",
            ),
            execution=ExecutionState(
                run_id=request.trace_id,
                graph_name="llm_runtime",
                status=RunStatus.SUCCEEDED,
                active_node="training_plan_llm",
                model_name="deepseek-chat",
            ),
            evidence=EvidenceState(route_names=["llm_only"]),
            guardrail=GuardrailState(
                risk_level=RiskLevel.LOW,
                completeness_ok=True,
                policy_ok=True,
            ),
            outcome=OutcomeState(
                intent="training_plan",
                answer="先练数组和哈希。",
                response_payload={
                    "current_level": "starter",
                    "target_direction": "algorithm_foundation",
                    "weak_points": "hash table",
                    "strong_points": "basic array iteration",
                    "plan_title": "Runtime Plan",
                    "plan_goal": "Stabilize hash map basics.",
                    "ai_summary": "Generated by model.",
                    "tasks": [
                        {
                            "task_type": "question",
                            "question_id": 101,
                            "exam_id": None,
                            "title_snapshot": "Two Sum",
                            "task_order": 1,
                            "recommended_reason": "Strengthen hash map basics.",
                            "knowledge_tags_snapshot": "hash table",
                            "due_time": None,
                        }
                    ],
                },
                write_intents=[
                    WriteIntent(
                        intent_type="training_plan_write",
                        target_service="oj-friend",
                        payload={"plan_title": "Runtime Plan"},
                    )
                ],
                status_events=[
                    {"node": "llm_prepare", "message": "已整理训练计划生成所需上下文。"},
                    {"node": "llm_inference", "message": "已完成训练计划推理。"},
                    {"node": "training_plan_llm", "message": "已校验并封装训练计划结果。"},
                ],
            ),
        ),
    )

    state = execute_training_plan_request(
        TrainingPlanRequest(
            trace_id="trace-training-runtime-001",
            user_id=1,
            current_level="starter",
            target_direction="algorithm_foundation",
            candidate_questions=[
                QuestionCandidate(
                    question_id=101,
                    title="Two Sum",
                    difficulty=1,
                    algorithm_tag="array",
                    knowledge_tags="hash table",
                    estimated_minutes=12,
                )
            ],
        )
    )

    assert state.execution.graph_name == "llm_runtime"
    assert state.execution.status is RunStatus.SUCCEEDED
    assert state.outcome.intent == "training_plan"
    assert state.outcome.response_payload["plan_title"]
    assert state.outcome.response_payload["tasks"]
    assert state.outcome.write_intents
    assert state.outcome.write_intents[0].intent_type == "training_plan_write"
    assert state.outcome.write_intents[0].target_service == "oj-friend"
