from pathlib import Path
import sys

from fastapi.testclient import TestClient


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from app.main import app  # noqa: E402
from app.runtime.enums import RiskLevel, RunStatus, TaskType  # noqa: E402
from app.runtime.models import (  # noqa: E402
    EvidenceState,
    ExecutionState,
    GuardrailState,
    OutcomeState,
    RequestContext,
    UnifiedAgentState,
)


client = TestClient(app)


def test_training_api_uses_llm_runtime(monkeypatch):
    import app.api.training as training_module  # noqa: WPS433

    monkeypatch.setattr(
        training_module,
        "execute_training_plan_request",
        lambda request: UnifiedAgentState(
            request=RequestContext(
                trace_id="trace-training-api-001",
                user_id="1",
                task_type=TaskType.TRAINING_PLAN,
                user_message="生成训练计划。",
            ),
            execution=ExecutionState(
                run_id="run-training-api-001",
                graph_name="llm_runtime",
                status=RunStatus.SUCCEEDED,
                active_node="training_plan_llm",
            ),
            evidence=EvidenceState(route_names=["llm_only"]),
            guardrail=GuardrailState(
                risk_level=RiskLevel.LOW,
                completeness_ok=True,
                policy_ok=True,
            ),
            outcome=OutcomeState(
                intent="training_plan",
                response_payload={
                    "current_level": "starter",
                    "target_direction": "algorithm_foundation",
                    "weak_points": "hash table",
                    "strong_points": "basic array iteration",
                    "plan_title": "Runtime Plan",
                    "plan_goal": "Stabilize hash map basics.",
                    "ai_summary": "Generated by runtime.",
                    "tasks": [
                        {
                            "task_type": "question",
                            "question_id": 101,
                            "exam_id": None,
                            "title_snapshot": "Two Sum",
                            "task_order": 1,
                            "recommended_reason": "Strengthen hash map basics.",
                            "knowledge_tags_snapshot": "hash table",
                            "due_time": None,
                        }
                    ],
                },
            ),
        ),
        raising=False,
    )

    response = client.post(
        "/api/training/plan",
        json={
            "trace_id": "trace-training-api-001",
            "user_id": 1,
            "current_level": "starter",
            "target_direction": "algorithm_foundation",
            "candidate_questions": [
                {
                    "question_id": 101,
                    "title": "Two Sum",
                    "difficulty": 1,
                    "algorithm_tag": "array",
                    "knowledge_tags": "hash table",
                    "estimated_minutes": 12,
                }
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["plan_title"] == "Runtime Plan"
    assert payload["tasks"][0]["title_snapshot"] == "Two Sum"


def test_training_api_returns_503_when_llm_runtime_unavailable(monkeypatch):
    import app.api.training as training_module  # noqa: WPS433

    monkeypatch.setattr(
        training_module,
        "execute_training_plan_request",
        lambda request: (_ for _ in ()).throw(RuntimeError("未配置可用的大模型。")),
        raising=False,
    )

    response = client.post(
        "/api/training/plan",
        json={
            "trace_id": "trace-training-api-002",
            "user_id": 1,
            "current_level": "starter",
            "target_direction": "algorithm_foundation",
            "candidate_questions": [],
        },
    )

    assert response.status_code == 503
    assert response.json()["detail"] == "未配置可用的大模型。"
