from datetime import datetime, timedelta

import pytest

from app.schemas.training_plan_request import QuestionCandidate, TrainingPlanRequest
from app.services.training_planner import build_training_plan


def test_build_training_plan_appends_stage_test_task_from_candidate_exams():
    now = datetime.now()
    request = TrainingPlanRequest(
        trace_id="phase2-test",
        user_id=1,
        current_level="starter",
        target_direction="algorithm_foundation",
        preferred_count=3,
        candidate_questions=[
            QuestionCandidate(
                question_id=101,
                title="Two Sum",
                difficulty=1,
                algorithm_tag="array",
                knowledge_tags="hash table",
                estimated_minutes=12,
            ),
            QuestionCandidate(
                question_id=102,
                title="Valid Parentheses",
                difficulty=1,
                algorithm_tag="stack",
                knowledge_tags="simulation",
                estimated_minutes=10,
            ),
        ],
        candidate_exams=[
            {
                "exam_id": 9001,
                "title": "Array And Hashing Checkpoint",
                "start_time": now - timedelta(hours=1),
                "end_time": now + timedelta(hours=2),
            }
        ],
    )

    plan = build_training_plan(request)

    test_tasks = [task for task in plan.tasks if task.task_type == "test"]

    assert len(test_tasks) == 1
    assert test_tasks[0].exam_id == 9001
    assert test_tasks[0].title_snapshot == "Array And Hashing Checkpoint"
    assert test_tasks[0].due_time is not None
    assert test_tasks[0].due_time == request.candidate_exams[0].end_time


def test_build_training_plan_prefers_llm_output_when_available(monkeypatch):
    from app.services import training_planner  # noqa: WPS433

    monkeypatch.setattr(
        training_planner,
        "_generate_plan_with_llm",
        lambda request, heuristic_plan: {
            "current_level": "advanced",
            "target_direction": "graph_search",
            "weak_points": "shortest path",
            "strong_points": "array basics",
            "plan_title": "LLM Graph Search Plan",
            "plan_goal": "Focus on shortest path stability.",
            "ai_summary": "Generated by model.",
            "tasks": [
                {
                    "task_type": "question",
                    "question_id": 101,
                    "exam_id": None,
                    "title_snapshot": "Two Sum",
                    "task_order": 1,
                    "recommended_reason": "Model selected task.",
                    "knowledge_tags_snapshot": "graph",
                }
            ],
        },
    )

    request = TrainingPlanRequest(
        trace_id="phase3-llm",
        user_id=1,
        current_level="starter",
        target_direction="algorithm_foundation",
        candidate_questions=[
            QuestionCandidate(
                question_id=101,
                title="Two Sum",
                difficulty=1,
                algorithm_tag="array",
                knowledge_tags="hash table",
                estimated_minutes=12,
            ),
        ],
    )

    plan = build_training_plan(request)

    assert plan.plan_title == "LLM Graph Search Plan"
    assert plan.current_level == "advanced"
    assert plan.tasks[0].recommended_reason == "Model selected task."


def test_build_training_plan_falls_back_to_heuristic_plan_when_llm_generation_fails(monkeypatch):
    from app.services import training_planner  # noqa: WPS433

    def raise_llm_failure(request, heuristic_plan):
        raise RuntimeError("llm unavailable")

    monkeypatch.setattr(training_planner, "_generate_plan_with_llm", raise_llm_failure)

    request = TrainingPlanRequest(
        trace_id="phase3-fallback",
        user_id=1,
        current_level="starter",
        target_direction="algorithm_foundation",
        candidate_questions=[
            QuestionCandidate(
                question_id=101,
                title="Two Sum",
                difficulty=1,
                algorithm_tag="array",
                knowledge_tags="hash table",
                estimated_minutes=12,
            ),
        ],
    )

    plan = build_training_plan(request)

    assert plan.plan_title == "Algorithm Foundation Training Plan"
    assert plan.tasks
